Repository beris147/whoami, pull requests merged in 2021-04, with the labels that each got.

#20 enforce strong typing in local modules imports
  .flowconfig
Labels: bug

#36 Tests for removing a User
  server/src/utils/__tests__/userUtils/removeUser.test.js
Labels: documentation, enhancement

#34 Tests for getting a user room
  server/src/utils/__tests__/userUtils/getUserRoom.test.js
Labels: documentation, enhancement

#39 room tests added
  client/src/components/Room.js
  client/src/components/__mocks__/MockRouter.js
  client/src/components/__tests__/Room.test.js
Labels: documentation, enhancement

#37 join room tests fixed
  client/src/components/Room.js
  client/src/components/__mocks__/MockRouter.js
  client/src/components/__tests__/JoinRoom.test.js
  client/src/components/__tests__/Room.test.js
Labels: bug, documentation, enhancement

#28 Create room tests
  client/src/components/JoinRoom.js
  client/src/components/Room.js
  client/src/components/__mocks__/ElementWithProviders.js
  client/src/components/__mocks__/MockRouter.js
  client/src/components/__tests__/CreateRoom.test.js
  client/src/components/__tests__/JoinRoom.test.js
  client/src/components/__tests__/Room.test.js
  client/src/utils/__mocks__/MockedSocketIO.js
Labels: documentation, enhancement

#25 App component tests added
  client/src/App.js
  client/src/__tests__/App.test.js
  client/src/components/JoinRoom.js
  client/src/components/Room.js
  client/src/components/__mocks__/ElementWithProviders.js
  client/src/components/__mocks__/MockRouter.js
  client/src/components/__tests__/CreateRoom.test.js
  client/src/components/__tests__/JoinRoom.test.js
  client/src/components/__tests__/Room.test.js
  client/src/index.js
  client/src/providers/__mocks__/MockedProvider.js
  client/src/providers/__tests__/MockedProvider.test.js
  client/src/tests/App.test.js
  client/src/tests/setupTests.js
  client/src/utils/__mocks__/MockedSocketIO.js
Labels: documentation, enhancement

#24 removed relative imports
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/__tests__/App.test.js
  client/src/components/CreateRoom.js
  client/src/components/JoinRoom.js
  client/src/components/Room.js
  client/src/components/__mocks__/ElementWithProviders.js
  client/src/components/__mocks__/MockRouter.js
  client/src/components/__tests__/CreateRoom.test.js
  client/src/components/__tests__/JoinRoom.test.js
  client/src/components/__tests__/Room.test.js
  client/src/index.js
  client/src/providers/SocketProvider.js
  client/src/providers/UserProvider.js
  client/src/providers/__mocks__/MockedProvider.js
  client/src/providers/__tests__/MockedProvider.test.js
  client/src/tests/App.test.js
  client/src/tests/setupTests.js
  client/src/utils/__mocks__/MockedSocketIO.js
  client/src/utils/routes.js
Labels: bug, enhancement

#38 Tests remove user from room
  server/src/utils/__tests__/userUtils/removeUserFromRoom.test.js
Labels: documentation, enhancement

#44 fixed multiple socket on event calls
  client/src/components/CreateRoom.js
  client/src/components/JoinRoom.js
  client/src/utils/__mocks__/MockedSocketIO.js
Labels: bug

#59 run tests before running server
  server/package-lock.json
  server/package.json
Labels: enhancement

#42 run tests pre-start and pre-build
  client/package.json
  server/package-lock.json
  server/package.json
Labels: enhancement

#41 simple home test added
  client/package.json
  client/src/components/__tests__/Home.test.js
  server/package-lock.json
  server/package.json
Labels: documentation, enhancement

#40 Minor tests fixes
  client/package.json
  client/src/components/__tests__/CreateRoom.test.js
  client/src/components/__tests__/Home.test.js
  client/src/components/__tests__/JoinRoom.test.js
  client/src/components/__tests__/Room.test.js
  server/package-lock.json
  server/package.json
Labels: bug, enhancement

#57 Remove by id tests
  server/src/utils/__tests__/userUtils/removeUserById.test.js
Labels: documentation, enhancement

#56 Remove user method
  server/src/sockets/handlers/roomHandler.js
  server/src/sockets/handlers/userHandler.js
  server/src/utils/__tests__/userUtils/removeUserById.test.js
  server/src/utils/__tests__/userUtils/removeUserFromRoom.test.js
  server/src/utils/roomUtils.js
  server/src/utils/userUtils.js
Labels: bug, enhancement

#51 basic chat client side with alerts
  client/src/App.js
  client/src/components/CreateRoom.js
  client/src/components/JoinRoom.js
  client/src/components/Room.js
Labels: enhancement

#50 Chat back end side
  client/src/App.js
  client/src/components/CreateRoom.js
  client/src/components/JoinRoom.js
  client/src/components/Room.js
  server/src/sockets/handlers/roomHandler.js
  server/src/utils/roomUtils.js
Labels: enhancement

#49 Message type
  client/src/App.js
  client/src/components/CreateRoom.js
  client/src/components/JoinRoom.js
  client/src/components/Room.js
  common/types.js
  common/types/messageType.js
  server/src/sockets/handlers/roomHandler.js
  server/src/utils/roomUtils.js
Labels: documentation, enhancement

#48 react warnings removed
  client/src/App.js
  client/src/components/CreateRoom.js
  client/src/components/JoinRoom.js
  client/src/components/Room.js
  common/types.js
  common/types/messageType.js
  server/src/sockets/handlers/roomHandler.js
  server/src/utils/roomUtils.js
Labels: enhancement

#47 basic toast notification added
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/CreateRoom.js
  client/src/components/JoinRoom.js
  client/src/components/Room.js
  client/src/utils/errorCallBack.js
  common/types.js
  common/types/messageType.js
  server/src/sockets/handlers/roomHandler.js
  server/src/utils/roomUtils.js
Labels: enhancement

#64 Create flow.yml
  .github/workflows/flow.yml
Labels: enhancement

#63 Create test.yml
  .github/workflows/flow.yml
  .github/workflows/test.yml
Labels: enhancement, question

#62 run test from root dir
  .github/workflows/flow.yml
  .github/workflows/test.yml
  package.json
  server/package.json
Labels: enhancement

#68 page not found added + page not found testing
  client/src/App.js
  client/src/components/PageNotFound.js
  client/src/components/__tests__/PageNotFound.test.js
Labels: enhancement

#77 npm run dev run tests only once
  package.json
Labels: bug

#70 call removeUserById when a users requests to leave the room
  server/src/sockets/handlers/roomHandler.js
Labels: bug

#69 change the workflows to only check when we push to master branch
  .github/workflows/flow.yml
  .github/workflows/jobs.yml
  .github/workflows/test.yml
Labels: bug

#79 send message, create and join rooms inputs handles enter event
  client/src/components/Chat/Chat.js
  client/src/components/CreateRoom.js
  client/src/components/JoinRoom.js
  client/src/components/__tests__/CreateRoom.test.js
  client/src/components/__tests__/JoinRoom.test.js
  client/src/utils/__test__/handleOnEnter.test.js
  client/src/utils/handleOnEnter.js
  client/src/utils/keycodes.js
Labels: enhancement

#78 basic chat, write, send and see messages on screen
  client/src/components/Chat/Chat.js
  client/src/components/Chat/MessageList.js
  client/src/components/CreateRoom.js
  client/src/components/JoinRoom.js
  client/src/components/Room.js
  client/src/components/__tests__/Chat/Chat.test.js
  client/src/components/__tests__/Chat/MessageList.test.js
  client/src/components/__tests__/CreateRoom.test.js
  client/src/components/__tests__/JoinRoom.test.js
  client/src/utils/__test__/handleOnEnter.test.js
  client/src/utils/handleOnEnter.js
  client/src/utils/keycodes.js
  common/types.js
  common/types/messageListType.js
Labels: enhancement

#83 Server forwards user-joined event to everyone in the room
  server/src/sockets/handlers/roomHandler.js
Labels: enhancement

#73 Forwards the event to the owner
  server/src/sockets/handlers/roomHandler.js
  server/src/utils/userUtils.js
Labels: enhancement

#81 Emit joined
  client/src/components/__tests__/lobby/JoinLobby.test.js
  client/src/components/__tests__/lobby/ServerAnswersUsersInLobby.test.js
  client/src/components/lobby/Lobby.js
  server/src/sockets/handlers/roomHandler.js
  server/src/utils/userUtils.js
Labels: enhancement

#75 Clients reply to get-users-in-lobby requests
  client/src/components/__tests__/lobby/GetUserInLobby.test.js
  client/src/components/__tests__/lobby/JoinLobby.test.js
  client/src/components/__tests__/lobby/ServerAnswersUsersInLobby.test.js
  client/src/components/lobby/Lobby.js
  common/types.js
  server/src/sockets/handlers/roomHandler.js
  server/src/utils/userUtils.js
Labels: enhancement

#61 Update ui when user join event is fired
  client/src/components/__tests__/CreateRoom.test.js
  client/src/components/__tests__/JoinRoom.test.js
  client/src/components/__tests__/lobby/GetUserInLobby.test.js
  client/src/components/__tests__/lobby/JoinLobby.test.js
  client/src/components/__tests__/lobby/ServerAnswersUsersInLobby.test.js
  client/src/components/__tests__/lobby/UserJoins.test.js
  client/src/components/lobby/Lobby.js
  client/src/components/lobby/UserList.js
  client/src/utils/__mocks__/MockedSocketIO.js
  common/types.js
  common/types/userInLobbyType.js
  common/types/usersInLobbyCallbackType.js
  server/src/sockets/handlers/roomHandler.js
  server/src/utils/userUtils.js
Labels: enhancement

#54 Adds Lobby component
  client/src/components/Room.js
  client/src/components/__tests__/CreateRoom.test.js
  client/src/components/__tests__/JoinRoom.test.js
  client/src/components/__tests__/lobby/GetUserInLobby.test.js
  client/src/components/__tests__/lobby/JoinLobby.test.js
  client/src/components/__tests__/lobby/ServerAnswersUsersInLobby.test.js
  client/src/components/__tests__/lobby/UserJoins.test.js
  client/src/components/lobby/Lobby.js
  client/src/components/lobby/PlayButton.js
  client/src/components/lobby/ReadyButton.js
  client/src/components/lobby/User.js
  client/src/components/lobby/UserList.js
  client/src/utils/__mocks__/MockedSocketIO.js
  common/types.js
  common/types/userInLobbyType.js
  common/types/userReadyStateType.js
  common/types/usersInLobbyCallbackType.js
  server/src/sockets/handlers/roomHandler.js
  server/src/utils/userUtils.js
Labels: enhancement
